{% set name = "presidio-analyzer" %}
{% set version = "2.2.358" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/presidio/archive/refs/tags/{{ version }}.tar.gz
  sha256: c6fdf07daa0af71abf40017f726abda6bebd82960a795906443ad5f661a922f6

build:
  noarch: python
  script: cd {{ name }} && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }},<4
    - spacy >=3.4.4,<4.0.0,!=3.7.0
    - regex
    - tldextract
    - pyyaml
    - phonenumbers >=8.12,<9.0.0
  run_constrained: # Optional packages
    - flask >=1.1
    - spacy_huggingface_pipelines
    - stanza
    - spacy_stanza
    - azure-ai-textanalytics
    - azure-core
    - gliner >=0.2.13,<1.0.0
    - transformers
    - huggingface_hub
    - gunicorn
    - onnxruntime-gpu >=1.19

test:
  imports:
    - presidio_analyzer
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip list
    - pip check

about:
  home: https://github.com/microsoft/presidio
  summary: 'Presidio Analyzer package'
  description: |
    Presidio Analyzer package.
  license: MIT
  license_file: LICENSE
  doc_url: https://microsoft.github.io/presidio
  dev_url: https://github.com/microsoft/presidio

extra:
  recipe-maintainers:
    - julcsii
    - geoHeil
    - heckert
